version: '3.8'

services:
  mysql-test:
    image: mysql:latest
    container_name: mysql-test
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mysql-test-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
